"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Security / environment
#
# These three come from the environment so nothing deployment-specific — and no
# real secret — lives in the repository. The defaults are the safe production
# ones; for local development set DJANGO_DEBUG=True.

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    # Placeholder for local development only. Render must set DJANGO_SECRET_KEY.
    "django-insecure-local-dev-only-not-for-production",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "False").strip().lower() == "true"

# Comma separated, e.g. "savora-api.onrender.com"
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

# Render injects the service's own hostname; trust it automatically so a first
# deploy does not fail with a 400 before DJANGO_ALLOWED_HOSTS has been filled in.
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "snippets",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # Serves collected static files (including the Django admin CSS) in
    # production. Must sit directly after SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "backend.urls"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "backend.wsgi.application"


# Database
#
# Render's filesystem is ephemeral: a SQLite file there is wiped on every deploy
# and restart, so production must use a managed database. Render's Postgres
# instance supplies DATABASE_URL; without it (local development) we fall back to
# the SQLite file exactly as before.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

_database_url = os.environ.get("DATABASE_URL", "").strip()
if _database_url:
    import dj_database_url

    DATABASES["default"] = dj_database_url.parse(
        _database_url,
        # Reuse connections between requests instead of reconnecting each time.
        conn_max_age=600,
        # Render's managed Postgres requires TLS.
        ssl_require=True,
    )


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = "static/"

# `collectstatic` writes here during the Render build; WhiteNoise serves from it.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    # Uploaded media stays on the local filesystem, exactly as before.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # The hashed-manifest storage needs collectstatic to have run, so it is only
    # used outside DEBUG; local development keeps Django's plain static serving.
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}


# CORS

CORS_ALLOWED_ORIGINS = [
    # Local Vite dev server
    "http://localhost:5174",
    # Deployed frontend on Vercel. Origins are scheme + host only: a trailing
    # slash makes Django's system checks fail with corsheaders.E014, which
    # aborts collectstatic during the Render build.
    "https://mahnoor-savora-one.vercel.app",
]

# Extra origins (e.g. Vercel preview deployments) without touching this file:
#   CORS_EXTRA_ORIGINS="https://preview-a.vercel.app,https://preview-b.vercel.app"
CORS_ALLOWED_ORIGINS += [
    origin.strip()
    for origin in os.environ.get("CORS_EXTRA_ORIGINS", "").split(",")
    if origin.strip()
]


# Django requires the frontend origin here for any cookie/session-authenticated
# POST/PUT/DELETE over HTTPS (e.g. the Django admin). The REST API itself uses
# bearer JWTs and is not CSRF-protected, so this is a safety net rather than a
# requirement for the current endpoints.
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)


# Django REST Framework

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


# Simple JWT
#
# The default access token lifetime is only 5 minutes, which expired while an
# admin was still filling in the edit form and made every save return 401.
# The frontend refreshes the access token using the refresh token.

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}


# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"