# Generated by Django 6.0.7 on 2026-07-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("guests", models.IntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("special_request", models.TextField(blank=True)),
            ],
        ),
    ]
