# Generated by Django 6.0.7 on 2026-09-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0004_replace_menu_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="allergens",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Crustaceans, Dairy",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="composition",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma separated, e.g. Native lobster, La Mancha saffron, Fennel pollen",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="energy",
            field=models.CharField(
                blank=True, default="", help_text="e.g. 640 kcal", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_chef_recommendation",
            field=models.BooleanField(
                default=False,
                help_text="Show the Chef's Recommendation badge for this dish.",
                verbose_name="Chef's Recommendation",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="pairing",
            field=models.CharField(
                blank=True, default="", help_text="e.g. Barolo 2009", max_length=200
            ),
        ),
    ]
