# Generated by Django 6.0.7 on 2026-09-12 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0005_menuitem_allergens_menuitem_composition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="JPG, JPEG, PNG or WEBP.",
                null=True,
                upload_to="menu_items/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
